version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "127.0.0.1:8501:8501"  # Only bind to localhost
    environment:
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - ./users.json:/app/users.json
      - user_data:/app/data  # Persistent data volume
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Certbot SSL certificates
    depends_on:
      - streamlit-app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  user_data:

networks:
  app-network:
    driver: bridge
